/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2a1700",
        "on-secondary-container": "#006f64",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-container": "#0f766e",
        "on-primary-fixed": "#00201d",
        "background": "#faf8ff",
        "secondary-fixed-dim": "#4fdbc8",
        "tertiary": "#734700",
        "surface-container-low": "#f2f3ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-error-container": "#93000a",
        "on-primary-container": "#a3faef",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#80d5cb",
        "inverse-surface": "#283044",
        "on-secondary-fixed": "#00201c",
        "on-surface": "#131b2e",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005048",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#00504a",
        "error-container": "#ffdad6",
        "secondary": "#006b5f",
        "secondary-container": "#6df5e1",
        "error": "#ba1a1a",
        "surface-container-highest": "#dae2fd",
        "surface-container": "#eaedff",
        "surface": "#faf8ff",
        "surface-tint": "#006a63",
        "outline": "#6e7977",
        "on-tertiary-container": "#ffe6cc",
        "primary-fixed": "#9cf2e8",
        "tertiary-container": "#945d00",
        "surface-variant": "#dae2fd",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#80d5cb",
        "surface-container-high": "#e2e7ff",
        "on-secondary": "#ffffff",
        "outline-variant": "#bdc9c6",
        "on-background": "#131b2e",
        "surface-dim": "#d2d9f4",
        "on-surface-variant": "#3e4947",
        "primary": "#005c55",
        "secondary-fixed": "#71f8e4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin": "2rem",
        "gutter-mobile": "0.75rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-xl": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "data-display": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-hero-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-xl": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "data-display": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
